// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NzWalks.API.Data;

#nullable disable

namespace NzWalks.API.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20230627193444_Image Update")]
    partial class ImageUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NzWalks.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Diffuculties");

                    b.HasData(
                        new
                        {
                            ID = new Guid("a48dc7a3-334c-473c-a995-50f5975414ec"),
                            CreatedDate = new DateTime(2023, 6, 27, 22, 34, 44, 75, DateTimeKind.Local).AddTicks(4691),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Easy",
                            Status = 1
                        },
                        new
                        {
                            ID = new Guid("5b8483c8-5a27-4c17-9b4e-30fb1553426c"),
                            CreatedDate = new DateTime(2023, 6, 27, 22, 34, 44, 75, DateTimeKind.Local).AddTicks(4726),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Medium",
                            Status = 1
                        },
                        new
                        {
                            ID = new Guid("d58a36f9-a5f2-437c-9436-c571149ed577"),
                            CreatedDate = new DateTime(2023, 6, 27, 22, 34, 44, 75, DateTimeKind.Local).AddTicks(4728),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hard",
                            Status = 1
                        });
                });

            modelBuilder.Entity("NzWalks.API.Models.Domain.Image", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("NzWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            ID = new Guid("f7248fc3-2585-4efb-8d1d-1c555f4087f6"),
                            Code = "AKL",
                            CreatedDate = new DateTime(2023, 6, 27, 22, 34, 44, 75, DateTimeKind.Local).AddTicks(4833),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Auckland",
                            RegionImageUrl = "https://images.pexels.com/photos/5169056/pexels-photo-5169056.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            Status = 1
                        },
                        new
                        {
                            ID = new Guid("6884f7d7-ad1f-4101-8df3-7a6fa7387d81"),
                            Code = "NTL",
                            CreatedDate = new DateTime(2023, 6, 27, 22, 34, 44, 75, DateTimeKind.Local).AddTicks(4837),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Northland",
                            Status = 1
                        },
                        new
                        {
                            ID = new Guid("14ceba71-4b51-4777-9b17-46602cf66153"),
                            Code = "BOP",
                            CreatedDate = new DateTime(2023, 6, 27, 22, 34, 44, 75, DateTimeKind.Local).AddTicks(4840),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bay Of Plenty",
                            Status = 1
                        },
                        new
                        {
                            ID = new Guid("cfa06ed2-bf65-4b65-93ed-c9d286ddb0de"),
                            Code = "WGN",
                            CreatedDate = new DateTime(2023, 6, 27, 22, 34, 44, 75, DateTimeKind.Local).AddTicks(4842),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Wellington",
                            RegionImageUrl = "https://images.pexels.com/photos/4350631/pexels-photo-4350631.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            Status = 1
                        },
                        new
                        {
                            ID = new Guid("906cb139-415a-4bbb-a174-1a1faf9fb1f6"),
                            Code = "NSN",
                            CreatedDate = new DateTime(2023, 6, 27, 22, 34, 44, 75, DateTimeKind.Local).AddTicks(4843),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nelson",
                            RegionImageUrl = "https://images.pexels.com/photos/13918194/pexels-photo-13918194.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            Status = 1
                        },
                        new
                        {
                            ID = new Guid("f077a22e-4248-4bf6-b564-c7cf4e250263"),
                            Code = "STL",
                            CreatedDate = new DateTime(2023, 6, 27, 22, 34, 44, 75, DateTimeKind.Local).AddTicks(4849),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Southland",
                            Status = 1
                        });
                });

            modelBuilder.Entity("NzWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("WalkImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DifficultyID")
                        .IsUnique();

                    b.HasIndex("RegionID")
                        .IsUnique();

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NzWalks.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("NzWalks.API.Models.Domain.Difficulty", "Difficulty")
                        .WithOne("Walk")
                        .HasForeignKey("NzWalks.API.Models.Domain.Walk", "DifficultyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NzWalks.API.Models.Domain.Region", "Region")
                        .WithOne("Walk")
                        .HasForeignKey("NzWalks.API.Models.Domain.Walk", "RegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("NzWalks.API.Models.Domain.Difficulty", b =>
                {
                    b.Navigation("Walk")
                        .IsRequired();
                });

            modelBuilder.Entity("NzWalks.API.Models.Domain.Region", b =>
                {
                    b.Navigation("Walk")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
